# Generated by Django 3.1.4 on 2021-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
