# Generated by Django 3.1.4 on 2021-01-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_comments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
